databases:
  # A PostgreSQL database instance on Render's free plan.
  - name: bitespeed-db
    databaseName: bitespeed_identity
    user: bitespeed_user
    plan: free

services:
  # The Node.js web service that runs the API.
  - type: web
    name: bitespeed-identity-api
    env: node
    plan: free
    # The build command installs dependencies, generates the Prisma client,
    # applies database migrations, and compiles the TypeScript code.
    buildCommand: "npm ci && npx prisma generate && npx prisma migrate deploy && npm run build"
    # The start command runs the compiled JavaScript server.
    startCommand: "npm run start"
    envVars:
      # The DATABASE_URL is automatically injected from the database service created above.
      # Render ensures this is a secure, internal connection string.
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString
      # Set the Node environment to production for performance optimizations.
      - key: NODE_ENV
        value: production
